name: UltraWarp
version: 0.0.1
main: net.plommer.UltraWarp.UltraWarp
author: [TheNokar]
softdepend: [Essentials, CommandBook]
loadbefore: [Essentials, CommandBook]
commands:
    warp:
        description: Default Warps command!
        aliases: [w, wa]
permissions:
    ultrawarp.*:
        description: Give access to all UltraWarps permissions!
        default: op
        children:
          ultrawarp.admin: true
    ultrawarp.admin:
        description: Give admin access
        default: op
        children:
          ultrawarp.use: true
    ultrawarp.user:
        description: Give user all norma permissions(Warp, Warp create, Warp modify, Warp remove)
        default: op
        children:
          ultrawarp.warp: true
          ultrawarp.warp.create: true
          ultrawarp.warp.remove: true
          ultrawarp.warp.modify: true
          ultrawarp.list: true
    ultrawarp.warp:
        description: Allows you to warp
        default: op
    ultrawarp.warp.create:
        description: Allows you to create warp
        default: op
    ultrawarp.warp.remove:
        description: Allows you to remove warp
        default: op
    ultrawarp.warp.list:
        description: Allows you to see a list of your warps!
        default: op